name: CI Workflow without cache

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: npm i
        
        - name: Start app with PM2
          run: |
            npm install -g pm2
            pm2 start index.js --name myapp
            pm2 save
            pm2 list