name: CI Workflow without cache

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: npm i
        
        - name: Run Application
          run: node index.js